### ISSUE TITLE
Data analysis for upcoming country reports & blogs

### ISSUE THREAD

**Issue by agrabeli** [OpenObservatory/OOHQ#4]
Data analysis based on the collected network measurements so far needs to be implemented for the following countries (to produce subsequent blogs and reports):

1. Zimbabwe
2. South Korea
3. Pakistan
4. Chile
5. Indonesia
6. Myanmar
7. Thailand

The data analysis would provide the following types of information:

1. Testing period (when the testing period started and "ended")
2. List of URLs that presented network anomalies.
3. Types of anomalies detected per URL (DNS, TCP/IP blocking, HTTP-failure, HTTP-diff).
4. Amount of anomalies detected per URL throughout the testing period. 
5. Ordering of anomalous URLs in a list starting from the ones that presented the highest amount of anomalies, ending to the ones that presented the lowest amount of anomalies (and which are more likely to be false positives).
6. IF POSSIBLE: control failure rate per anomalous URL.

**Comment by agrabeli** [comment]
PRIORITY should be given to Indonesia, Thailand, and Myanmar, so that those findings can potentially be presented/discussed at RightsCon.

**Comment by hellais** [comment]
Data analysis for ID, TH and MM has been done.

**Comment by hellais** [comment]
I am closing this in favour of using trello for tracking data analysis related tasks.
